library(shiny)
library(tidyverse)
library(readxl)
library(lubridate)

# UI - user interface
ui <- fluidPage(
  
  # sidebar on the left where users can select info
  sidebar = sidebar(
    
    # include description of purpose somewhere
    # include template Excel sheet for people to download from
    
    # accept Excel sheet from 
    fileInput("upload", "Upload Excel Sheet", accept = c(".xlsx", ".xls")),
    
    # initial dropdown for variable selection
    selectInput("variable", "Select Variable Type to Analyze:",
                choices = c("Rolls by Die Type" = "die_type",
                            "Rolls by Die Set" = "die_set",
                            "Rolls by Campaign" = "campaign",
                            "Rolls by Session" = "session",
                            "Rolls Over Time" = "date")),
    
    # create a second drop down for each choice
    # die_type conditional panel for second drop down 
    conditionalPanel(
      condition = "input.variable == die_type",
      selectInput("selected_type", "Select Die Type:", 
                  choices = c("d4", "d6", "d8", "d10", "d%%", "d12", "d20"))
    ),
    
    # die_set conditional panel for second drop down
    conditionalPanel(
      condition = "input.variable == die_set",
      selectInput("selected_set", "Select Die Set:")
      # need to make it either text 
      #or read the input dataset and give dependent options
    )
    
    # filter ID_Number by campaign and session for conditional payments
    
    # date conditional panel for second drop down
    # maybe range or just one date?
  )
  
)

# server - backend
server <- function(input, output, session){
  
  # Read and process uploaded data
  dice_data <- reactive({
    req(input$upload)
    
    df <- read_excel(input$upload$datapath)
    df$Date <- as.Date(df$Date)
    return(df)
    
  })
  
  # Generate the plot based on user input
  output$dice_plot <- renderPlot({
    req(dice_data())
    
    # renders plots based on user-specified die_type
    if (input$variable == "die_type"){
      req(input$selected_type)
      
      data <- dice_data()
      
      # plotting DieRoll by DieType
      ggplot(data %>% filter = DieType == input$selected_type, 
             mapping = aes(x = DieRoll)) +
        # fill by what? options?
        geom_bar(aes(fill = DieSet)) +
        labs(title = paste("Distribution of", input$selected_type, "Rolls"),
             x = "Roll Value",
             y = "Number of Times Rolled")
      # add scale somehow for each graph
      
      # renders plots based on user-specified die_set
    } else if (input$variable == "die_set"){
      req(input$selected_set)
      
      data <- dice_data()
      
      # plotting DieRoll by DieSet
      ggplot(data %>% filter = DieSet = input$selected_set,
             mapping = aes(x = DieRoll)) +
        geom_bar() +
        # offer option to only do one DieType?
        facet_wrap(~DieType, scales = "free_x") +
        labs(title = paste("Distribution of", input$selected_set, "Set"),
             x = "Roll Value",
             y = "Number of Time Rolled")
    }
  })
}

shinyApp(ui, server)

# do I add another dropdown to give option for color 
# or just give the user every combo?

# add captions to say "generated by app made by MYNAME"

# make persons able to download plot?

# make plots interactive

# be able to share link

# tabsets on the right (tabs: plots, tables, summary)

# conditional formatting for DieType, DieSet, Campaign, Session, Date