library(shiny)
library(tidyverse)
library(readxl)
library(lubridate)
library(bslib)

# UI - user interface
ui <- page_sidebar(
  title = "D&D Dice Roll Analysis",
  
  # sidebar on the left where users can select info
  sidebar = sidebar(
    
    # include description of purpose somewhere
    # include template Excel sheet for people to download from
    
    # accept Excel sheet from 
    fileInput("upload", "Upload Excel Sheet", accept = c(".xlsx", ".xls")),
    
    # initial dropdown for variable selection
    selectInput("variable", "Select Variable Type to Analyze:",
                choices = c("Rolls by Die Type" = "die_type",
                            "Rolls by Die Set" = "die_set",
                            "Rolls by Campaign" = "campaign",
                            "Rolls by Session" = "sess",
                            "Rolls Over Time" = "date")),
    
    # create a second drop down for each choice
    # die_type conditional panel for second drop down 
    conditionalPanel(
      condition = "input.variable == 'die_type'",
      selectInput("selected_type", "Select Die Type:", 
                  choices = c("d4", "d6", "d8", "d10", "d%%", "d12", "d20"))
    ),
    
    # die_set conditional panel for second drop down
    conditionalPanel(
      condition = "input.variable == 'die_set'",
      selectInput("selected_set", "Select Die Set:",
                  choices = NULL)
      # need to make it either text 
      # or read the input dataset and give dependent options
    ),
    
    # campaign conditional panel for second drop down
    conditionalPanel(
      condition = "input.variable == 'campaign'",
      selectInput("selected_campaign", "Select Campaign ID:",
                  choices = NULL)
    )
    
    # filter ID_Number by campaign and session for conditional payments
  
  ),
  
  # main panel with plot output
  card(
    card_header("Dice Roll Distribution"),
    plotOutput("dice_plot")
    # date conditional panel for second drop down
    # maybe range or just one date?

  )
  
)
  

# server - backend
server <- function(input, output, session){
  
  # Read and process uploaded data
  dice_data <- reactive({
    req(input$upload)
    df <- read_excel(input$upload$datapath)
    return(df)
    
  })
  
  # update choices based on uploaded data for DieType
  observe({
    req(dice_data())
    updateSelectInput(session, "selected_type",
                      choices = unique(dice_data()$DieType))
  })
  
  # update choices based on uploaded data for DieSet
  observe({
    req(dice_data())
    updateSelectInput(session, "selected_set",
                      choices = unique(dice_data()$DieSet))
  })
  
  # Generate the plot based on user input
  output$dice_plot <- renderPlot({
    req(dice_data())
    
    # renders plots based on user-specified die_type
    if (input$variable == "die_type"){
      req(input$selected_type)
      
      # plotting DieRoll by DieType
      ggplot(dice_data() %>% filter(DieType == input$selected_type), 
             aes(x = DieRoll)) +
        # fill by what? options?
        geom_bar() + 
        labs(title = paste("Distribution of", input$selected_type, "Rolls"),
             x = "Roll Value",
             y = "Number of Times Rolled")
      # add scale somehow for each graph, hardset scale for each die type
      # dropdown dependent on order produced by excel sheet, order it by number
      # make scale free
      
      # renders plots based on user-specified die_set
    } else if (input$variable == "die_set"){
      req(input$selected_set)
      
      # plotting DieRoll by DieSet
      ggplot(dice_data() %>% filter(DieSet == input$selected_set),
             aes(x = DieRoll)) +
        geom_bar() +
        # offer option to only do one DieType?
        facet_wrap(~DieType, scales = "free") +
        labs(title = paste("Distribution of", input$selected_set, "Set"),
             x = "Roll Value",
             y = "Number of Time Rolled")
    }
  })
}

shinyApp(ui, server)

# do I add another dropdown to give option for color 
# or just give the user every combo?

# add captions to say "generated by app made by MYNAME"

# make persons able to download plot?

# make plots interactive

# be able to share link

# tabsets on the right (tabs: plots, tables, summary)

# conditional formatting for DieType, DieSet, Campaign, Session, Date